# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(True)

# Allow JavaScript to read from or write to the clipboard. With
# QtWebEngine, writing the clipboard as response to a user interaction
# is always allowed. On Qt < 6.8, the `ask` setting is equivalent to
# `none` and permission needs to be granted manually via this setting.
# Type: JSClipboardPermission
# Valid values:
#   - none: Disable access to clipboard.
#   - access: Allow reading from and writing to the clipboard.
#   - access-paste: Allow accessing the clipboard and pasting clipboard content.
#   - ask: Prompt when requested (grants 'access-paste' permission).
c.content.javascript.clipboard = 'access'

# Enable JavaScript.
config.set('content.javascript.enabled', True, 'chrome-devtools://*')
config.set('content.javascript.enabled', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'chrome://*/*')
config.set('content.javascript.enabled', True, 'qute://*/*')

# Custom

## theme
config.source("gruvbox.py")

## bangs
c.url.searchengines = {
    "DEFAULT": "https://duckduckgo.com/lite?q={}",
    "ddg": "https://duckduckgo.com/lite?q={}",
    "g": "https://www.google.com/search?hl=en&udm=14&q={}",
    "toys": "https://toys.whereis.social/?search={}&channel=",
    "arch": "https://wiki.archlinux.org/index.php?search={}&profile=default&fulltext=1",
    "yt": "https://www.youtube.com/results?search_query={}",
    "gh": "https://github.com/search?utf8=✓&s=stars&q={}",
    "ghc": "https://github.com/search?utf8=✓&type=Code&q={}",
}


## keybindings
config.unbind("d")
config.bind(';V', 'spawn mpv {url}')
config.bind(';v', 'hint links spawn mpv {hint-url}')
