" Core
set nocompatible
set ttimeout
set ttimeoutlen=1
set ttyfast
set encoding=utf-8
set splitbelow splitright
set mouse=a
set clipboard=unnamed,unnamedplus
set shortmess-=S
set laststatus=2
set showcmd
set showmode
set ruler
set hidden

" UI
syntax on
filetype plugin indent on
set background=light
set number
set relativenumber

" Search
set hlsearch
set incsearch
set smartcase
