" cursor
silent !echo -ne "\e[2 q"
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"

" Core
set nocompatible
set ttimeout
set ttimeoutlen=1
set ttyfast
set encoding=utf-8
set splitbelow splitright
set mouse=a
set clipboard=unnamed,unnamedplus
set shortmess-=S
set laststatus=2
set showcmd
set showmode
set ruler
set hidden

" UI
syntax on
filetype plugin indent on
set background=light
set number
set relativenumber
" Search
set hlsearch
set incsearch
set smartcase
