;;; gruvbox-theme.el --- gruvbox theme -*- lexical-binding: t; -*-

;; Author: Henrik Lissner and the doom-themes contributors
;; Palette: gruvbox by Pavel Pertsev <https://github.com/morhetz/gruvbox>
;; URL: https://github.com/doomemacs/themes
;; License: MIT

;;; Commentary:
;;
;; Standalone, dependency-free port of the `doom-gruvbox' theme from
;; `doom-themes' (v2.3.0).  Colors are bound to a named palette below and
;; referenced throughout, so tweaking the theme means editing one variable.
;; Two personal overrides are baked in: function names use yellow and types
;; use violet.

;;; Code:

(deftheme gruvbox
  "Dark theme with retro-groove gruvbox colors.")

(let* (
       ;; Core palette
       (gruvbox-bg             "#282828")
       (gruvbox-bg-alt         "#1d2021")
       (gruvbox-bg-alt2        "#504945")
       (gruvbox-base0          "#0d1011")
       (gruvbox-base3          "#3c3836")
       (gruvbox-base4          "#665c54")
       (gruvbox-base5          "#7c6f64")
       (gruvbox-base6          "#928374")
       (gruvbox-base7          "#d5c4a1")
       (gruvbox-base8          "#fbf1c7")
       (gruvbox-fg             "#ebdbb2")
       (gruvbox-modeline-bg    "#37302f")
       (gruvbox-red            "#fb4934")
       (gruvbox-dark-red       "#cc241d")
       (gruvbox-orange         "#fe8019")
       (gruvbox-yellow         "#fabd2f")
       (gruvbox-green          "#b8bb26")
       (gruvbox-teal           "#8ec07c")
       (gruvbox-blue           "#83a598")
       (gruvbox-dark-blue      "#458588")
       (gruvbox-violet         "#d3869b")
       (gruvbox-dark-cyan      "#689d6a")
       (gruvbox-doc-comments   "#dfd2b8")
       (gruvbox-vc-added       "#9c9e20")
       (gruvbox-vc-modified    "#78a369")
       (gruvbox-vc-deleted     "#d53e2c")

       ;; Extended / blended shades (ordered dark -> light)
       (gruvbox-grey1          "#191c1d")
       (gruvbox-grey2          "#1a1c1d")
       (gruvbox-grey3          "#1a1d1e")
       (gruvbox-grey4          "#1b1e1f")
       (gruvbox-grey5          "#1c1f20")
       (gruvbox-grey6          "#382726")
       (gruvbox-grey7          "#313131")
       (gruvbox-grey8          "#333327")
       (gruvbox-grey9          "#323232")
       (gruvbox-grey10         "#3d3026")
       (gruvbox-grey11         "#313433")
       (gruvbox-grey12         "#363627")
       (gruvbox-grey13         "#3c3628")
       (gruvbox-grey14         "#3f3f26")
       (gruvbox-grey15         "#4b3834")
       (gruvbox-grey16         "#3a413e")
       (gruvbox-grey17         "#3b4744")
       (gruvbox-grey18         "#50625c")
       (gruvbox-grey19         "#acbaa2")
       (gruvbox-grey20         "#a8c0b6")
       (gruvbox-red1           "#522e2a")
       (gruvbox-red2           "#5f2c26")
       (gruvbox-red4           "#5a3934")
       (gruvbox-red5           "#623b35")
       (gruvbox-red6           "#7c352c")
       (gruvbox-red7           "#8b342a")
       (gruvbox-red8           "#aa3123")
       (gruvbox-red10          "#db3024")
       (gruvbox-red11          "#dc421b")
       (gruvbox-red12          "#d3443e")
       (gruvbox-red13          "#eb3c2c")
       (gruvbox-red14          "#e05744")
       (gruvbox-red15          "#c66554")
       (gruvbox-red16          "#ac7464")
       (gruvbox-red17          "#db6560")
       (gruvbox-red18          "#d86d58")
       (gruvbox-red19          "#fb6452")
       (gruvbox-orange1        "#523924")
       (gruvbox-orange2        "#5f4f25")
       (gruvbox-orange4        "#8b6e28")
       (gruvbox-orange5        "#7c6f62")
       (gruvbox-orange6        "#cb6614")
       (gruvbox-orange7        "#89816d")
       (gruvbox-orange8        "#ed611a")
       (gruvbox-orange13       "#fc9420")
       (gruvbox-orange14       "#bcaf8e")
       (gruvbox-orange15       "#fba827")
       (gruvbox-orange16       "#c4b796")
       (gruvbox-orange18       "#cec09c")
       (gruvbox-orange19       "#fac64e")
       (gruvbox-orange20       "#f3c963")
       (gruvbox-yellow1        "#444527")
       (gruvbox-yellow2        "#7c7e19")
       (gruvbox-yellow4        "#cebb29")
       (gruvbox-yellow5        "#c2c546")
       (gruvbox-yellow6        "#e3bc2c")
       (gruvbox-yellow7        "#ccc75e")
       (gruvbox-green1         "#8db58f")
       (gruvbox-green2         "#95b2a7")
       (gruvbox-green3         "#97c281")
       (gruvbox-green4         "#9ec98f")
       (gruvbox-green5         "#b3ca91")
       (gruvbox-green7         "#b3ceb4")
       (gruvbox-green8         "#bbd9b0")
       (gruvbox-magenta1       "#7e505d")
       (gruvbox-magenta3       "#db9eaf")
       (gruvbox-magenta4       "#e0aab9")
       (gruvbox-magenta5       "#e4b6c3")
       (gruvbox-magenta6       "#edced7")
       )

  (custom-theme-set-faces
   'gruvbox
   `(TeX-error-description-error ((t (:inherit error :weight bold))))
   `(TeX-error-description-tex-said ((t (:inherit success :weight bold))))
   `(TeX-error-description-warning ((t (:inherit warning :weight bold))))
   `(ansi-color-black ((t (:foreground ,gruvbox-bg :background ,gruvbox-bg))))
   `(ansi-color-blue ((t (:foreground ,gruvbox-blue :background ,gruvbox-blue))))
   `(ansi-color-bright-black ((t (:foreground ,gruvbox-base0 :background ,gruvbox-bg))))
   `(ansi-color-bright-blue ((t (:foreground ,gruvbox-green2 :background ,gruvbox-green2))))
   `(ansi-color-bright-cyan ((t (:foreground ,gruvbox-green4 :background ,gruvbox-green4))))
   `(ansi-color-bright-green ((t (:foreground ,gruvbox-yellow5 :background ,gruvbox-yellow5))))
   `(ansi-color-bright-magenta ((t (:foreground ,gruvbox-red12 :background ,gruvbox-red12))))
   `(ansi-color-bright-red ((t (:foreground ,gruvbox-red19 :background ,gruvbox-red19))))
   `(ansi-color-bright-white ((t (:foreground ,gruvbox-base8 :background ,gruvbox-base8))))
   `(ansi-color-bright-yellow ((t (:foreground ,gruvbox-orange19 :background ,gruvbox-orange19))))
   `(ansi-color-cyan ((t (:foreground ,gruvbox-teal :background ,gruvbox-teal))))
   `(ansi-color-green ((t (:foreground ,gruvbox-green :background ,gruvbox-green))))
   `(ansi-color-magenta ((t (:foreground ,gruvbox-dark-red :background ,gruvbox-dark-red))))
   `(ansi-color-red ((t (:foreground ,gruvbox-red :background ,gruvbox-red))))
   `(ansi-color-white ((t (:foreground ,gruvbox-fg :background ,gruvbox-fg))))
   `(ansi-color-yellow ((t (:foreground ,gruvbox-yellow :background ,gruvbox-yellow))))
   `(anzu-replace-highlight ((t (:background ,gruvbox-base0 :foreground ,gruvbox-red :weight bold :strike-through t))))
   `(anzu-replace-to ((t (:background ,gruvbox-base0 :foreground ,gruvbox-green :weight bold))))
   `(bold ((t (:weight bold :foreground unspecified))))
   `(bold-italic ((t (:inherit (bold italic)))))
   `(button ((t (:foreground ,gruvbox-teal :underline t :weight bold))))
   `(compilation-column-number ((t (:inherit font-lock-comment-face))))
   `(compilation-error ((t (:inherit error :weight bold))))
   `(compilation-info ((t (:inherit success))))
   `(compilation-line-number ((t (:foreground ,gruvbox-yellow))))
   `(compilation-mode-line-exit ((t (:inherit compilation-info))))
   `(compilation-mode-line-fail ((t (:inherit compilation-error))))
   `(compilation-warning ((t (:inherit warning :slant italic))))
   `(corfu-current ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg))))
   `(corfu-default ((t (:inherit tooltip))))
   `(cursor ((t (:background "white"))))
   `(custom-button ((t (:foreground ,gruvbox-blue :background ,gruvbox-bg :box (:line-width 1 :style nil)))))
   `(custom-button-mouse ((t (:foreground ,gruvbox-bg :background ,gruvbox-blue :box (:line-width 1 :style nil)))))
   `(custom-button-pressed ((t (:foreground ,gruvbox-bg :background ,gruvbox-blue :box (:line-width 1 :style nil)))))
   `(custom-button-pressed-unraised ((t (:foreground ,gruvbox-bg :background ,gruvbox-violet :box (:line-width 1 :style nil)))))
   `(custom-button-unraised ((t (:foreground ,gruvbox-violet :background ,gruvbox-bg :box (:line-width 1 :style nil)))))
   `(custom-changed ((t (:foreground ,gruvbox-blue :background ,gruvbox-bg))))
   `(custom-comment ((t (:foreground ,gruvbox-fg :background ,gruvbox-bg-alt2))))
   `(custom-comment-tag ((t (:foreground ,gruvbox-base6))))
   `(custom-group-subtitle ((t (:foreground ,gruvbox-red))))
   `(custom-group-tag ((t (:foreground ,gruvbox-violet))))
   `(custom-group-tag-1 ((t (:foreground ,gruvbox-blue))))
   `(custom-invalid ((t (:foreground ,gruvbox-red :background ,gruvbox-red1))))
   `(custom-modified ((t (:foreground ,gruvbox-blue :background ,gruvbox-grey16))))
   `(custom-saved ((t (:foreground ,gruvbox-green :background ,gruvbox-yellow1 :bold t))))
   `(custom-set ((t (:foreground ,gruvbox-yellow :background ,gruvbox-bg))))
   `(custom-state ((t (:foreground ,gruvbox-green :background ,gruvbox-yellow1))))
   `(custom-themed ((t (:foreground ,gruvbox-yellow :background ,gruvbox-bg))))
   `(custom-variable-button ((t (:foreground ,gruvbox-green :underline t))))
   `(custom-variable-obsolete ((t (:foreground ,gruvbox-base6 :background ,gruvbox-bg))))
   `(custom-variable-tag ((t (:foreground ,gruvbox-dark-red))))
   `(custom-visibility ((t (:foreground ,gruvbox-blue :underline unspecified))))
   `(default ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg))))
   `(diff-added ((t (:inherit hl-line :foreground ,gruvbox-green))))
   `(diff-changed ((t (:foreground ,gruvbox-violet))))
   `(diff-context ((t (:foreground ,gruvbox-orange18))))
   `(diff-file-header ((t (:foreground ,gruvbox-blue))))
   `(diff-header ((t (:foreground ,gruvbox-teal))))
   `(diff-hl-change ((t (:foreground ,gruvbox-vc-modified :background ,gruvbox-vc-modified))))
   `(diff-hl-delete ((t (:foreground ,gruvbox-vc-deleted :background ,gruvbox-vc-deleted))))
   `(diff-hl-insert ((t (:foreground ,gruvbox-vc-added :background ,gruvbox-vc-added))))
   `(diff-hunk-header ((t (:foreground ,gruvbox-violet))))
   `(diff-refine-added ((t (:inherit diff-added :inverse-video t))))
   `(diff-refine-changed ((t (:inherit diff-changed :inverse-video t))))
   `(diff-refine-removed ((t (:inherit diff-removed :inverse-video t))))
   `(diff-removed ((t (:foreground ,gruvbox-red :background ,gruvbox-base3))))
   `(dired-directory ((t (:foreground ,gruvbox-teal))))
   `(dired-flagged ((t (:foreground ,gruvbox-red))))
   `(dired-header ((t (:foreground ,gruvbox-teal))))
   `(dired-ignored ((t (:foreground ,gruvbox-base6))))
   `(dired-k-added ((t (:foreground ,gruvbox-vc-added :weight bold))))
   `(dired-k-commited ((t (:foreground ,gruvbox-green :weight bold))))
   `(dired-k-directory ((t (:foreground ,gruvbox-blue :weight bold))))
   `(dired-k-ignored ((t (:foreground ,gruvbox-base5 :weight bold))))
   `(dired-k-modified ((t (:foreground ,gruvbox-vc-modified :weight bold))))
   `(dired-k-untracked ((t (:foreground ,gruvbox-teal :weight bold))))
   `(dired-mark ((t (:foreground ,gruvbox-orange :weight bold))))
   `(dired-marked ((t (:foreground ,gruvbox-yellow))))
   `(dired-perm-write ((t (:foreground ,gruvbox-fg :underline t))))
   `(dired-subtree-depth-1-face ((t (:background ,gruvbox-grey5))))
   `(dired-subtree-depth-2-face ((t (:background ,gruvbox-grey4))))
   `(dired-subtree-depth-3-face ((t (:background ,gruvbox-grey4))))
   `(dired-subtree-depth-4-face ((t (:background ,gruvbox-grey3))))
   `(dired-subtree-depth-5-face ((t (:background ,gruvbox-grey2))))
   `(dired-subtree-depth-6-face ((t (:background ,gruvbox-grey1))))
   `(dired-symlink ((t (:foreground ,gruvbox-teal))))
   `(dired-warning ((t (:foreground ,gruvbox-yellow))))
   `(ediff-current-diff-A ((t (:background ,gruvbox-red1))))
   `(ediff-current-diff-B ((t (:inherit ediff-current-diff-A))))
   `(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
   `(ediff-even-diff-A ((t (:inherit hl-line))))
   `(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
   `(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
   `(ediff-fine-diff-A ((t (:background ,gruvbox-red6 :weight bold))))
   `(ediff-fine-diff-B ((t (:inherit ediff-fine-diff-A))))
   `(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
   `(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
   `(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
   `(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
   `(embark-target ((t (:background ,gruvbox-bg-alt2 :extend t))))
   `(error ((t (:foreground ,gruvbox-red))))
   `(escape-glyph ((t (:foreground ,gruvbox-teal))))
   `(evil-ex-info ((t (:foreground ,gruvbox-red :slant italic))))
   `(evil-ex-search ((t (:background ,gruvbox-yellow :foreground ,gruvbox-base0 :weight bold))))
   `(evil-ex-substitute-matches ((t (:background ,gruvbox-base0 :foreground ,gruvbox-red :weight bold :strike-through t))))
   `(evil-ex-substitute-replacement ((t (:foreground ,gruvbox-teal :strike-through nil :inherit evil-ex-substitute-matches))))
   `(evil-goggles-default-face ((t (:inherit region :background ,gruvbox-base3))))
   `(evil-mc-cursor-bar-face ((t (:height 1 :background ,gruvbox-dark-red :foreground ,gruvbox-base0))))
   `(evil-mc-cursor-default-face ((t (:background ,gruvbox-dark-red :foreground ,gruvbox-base0))))
   `(evil-mc-cursor-hbar-face ((t (:underline (:color ,gruvbox-yellow)))))
   `(evil-mc-region-face ((t (:inherit region))))
   `(evil-search-highlight-persist-highlight-face ((t (:background ,gruvbox-yellow))))
   `(evil-snipe-first-match-face ((t (:foreground "white" :background ,gruvbox-yellow))))
   `(evil-snipe-matches-face ((t (:foreground ,gruvbox-yellow :bold t :underline t))))
   `(flymake-error ((t (:underline (:style wave :color ,gruvbox-red)))))
   `(flymake-note ((t (:underline (:style wave :color ,gruvbox-green)))))
   `(flymake-warning ((t (:underline (:style wave :color ,gruvbox-orange)))))
   `(font-latex-bold-face ((t (:inherit bold))))
   `(font-latex-italic-face ((t (:inherit italic))))
   `(font-latex-math-face ((t (:foreground ,gruvbox-dark-cyan))))
   `(font-latex-script-char-face ((t (:foreground ,gruvbox-dark-blue))))
   `(font-latex-sectioning-0-face ((t (:foreground ,gruvbox-blue :weight ultra-bold))))
   `(font-latex-sectioning-1-face ((t (:foreground ,gruvbox-dark-red :weight semi-bold))))
   `(font-latex-sectioning-2-face ((t (:foreground ,gruvbox-violet :weight semi-bold))))
   `(font-latex-sectioning-3-face ((t (:foreground ,gruvbox-grey20 :weight semi-bold))))
   `(font-latex-sectioning-4-face ((t (:foreground ,gruvbox-red17 :weight semi-bold))))
   `(font-latex-sectioning-5-face ((t (:foreground ,gruvbox-magenta4 :weight semi-bold))))
   `(font-latex-string-face ((t (:inherit font-lock-string-face))))
   `(font-latex-verbatim-face ((t (:inherit fixed-pitch :foreground ,gruvbox-violet :slant italic))))
   `(font-latex-warning-face ((t (:inherit font-lock-warning-face))))
   `(font-lock-builtin-face ((t (:foreground ,gruvbox-orange))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-comment-face ((t (:foreground ,gruvbox-base6))))
   `(font-lock-constant-face ((t (:foreground ,gruvbox-violet))))
   `(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground ,gruvbox-doc-comments))))
   `(font-lock-function-name-face ((t (:foreground ,gruvbox-yellow))))
   `(font-lock-keyword-face ((t (:foreground ,gruvbox-red))))
   `(font-lock-negation-char-face ((t (:inherit bold :foreground ,gruvbox-fg))))
   `(font-lock-number-face ((t (:foreground ,gruvbox-violet))))
   `(font-lock-preprocessor-char-face ((t (:inherit bold :foreground ,gruvbox-fg))))
   `(font-lock-preprocessor-face ((t (:inherit bold :foreground ,gruvbox-fg))))
   `(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground ,gruvbox-fg))))
   `(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground ,gruvbox-fg))))
   `(font-lock-string-face ((t (:foreground ,gruvbox-green))))
   `(font-lock-type-face ((t (:foreground ,gruvbox-violet))))
   `(font-lock-variable-name-face ((t (:foreground ,gruvbox-blue))))
   `(font-lock-warning-face ((t (:inherit warning))))
   `(fringe ((t (:inherit default :foreground ,gruvbox-base4))))
   `(git-commit-comment-action ((t nil)))
   `(git-commit-comment-branch-local ((t (:foreground ,gruvbox-dark-red))))
   `(git-commit-comment-branch-remote ((t (:foreground ,gruvbox-green))))
   `(git-commit-comment-detached ((t (:foreground ,gruvbox-orange))))
   `(git-commit-comment-file ((t (:foreground ,gruvbox-violet))))
   `(git-commit-comment-heading ((t (:foreground ,gruvbox-red))))
   `(git-commit-keyword ((t (:foreground ,gruvbox-teal :slant italic))))
   `(git-commit-known-pseudo-header ((t (:foreground ,gruvbox-doc-comments :weight bold :slant italic))))
   `(git-commit-nonempty-second-line ((t (:inherit git-commit-overlong-summary))))
   `(git-commit-overlong-summary ((t (:inherit error :background ,gruvbox-base0 :slant italic :weight bold))))
   `(git-commit-pseudo-header ((t (:foreground ,gruvbox-doc-comments :slant italic))))
   `(git-commit-summary ((t (:foreground ,gruvbox-green))))
   `(header-line ((t (:inherit mode-line))))
   `(header-line-highlight ((t (:inherit mode-line-highlight))))
   `(helpful-heading ((t (:weight bold :height 1.2))))
   `(highlight ((t (:background ,gruvbox-yellow :foreground ,gruvbox-base0 :distant-foreground ,gruvbox-base8))))
   `(hl-line ((t (:background ,gruvbox-base3))))
   `(iedit-occurrence ((t (:foreground ,gruvbox-dark-red :weight bold :inverse-video t))))
   `(iedit-read-only-occurrence ((t (:inherit region))))
   `(isearch ((t (:foreground ,gruvbox-base0 :background ,gruvbox-orange))))
   `(isearch-fail ((t (:background ,gruvbox-red :foreground ,gruvbox-base0 :weight bold))))
   `(italic ((t (:slant italic))))
   `(lazy-highlight ((t (:background ,gruvbox-yellow :foreground ,gruvbox-base0 :distant-foreground ,gruvbox-base0 :bold t))))
   `(line-number ((t (:inherit default :foreground ,gruvbox-base5 :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified))))
   `(line-number-current-line ((t (:inherit (hl-line default) :foreground ,gruvbox-yellow :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified :background ,gruvbox-base3))))
   `(link ((t (:foreground ,gruvbox-violet :underline t :weight bold))))
   `(magit-bisect-bad ((t (:foreground ,gruvbox-red))))
   `(magit-bisect-good ((t (:foreground ,gruvbox-green))))
   `(magit-bisect-skip ((t (:foreground ,gruvbox-orange))))
   `(magit-blame-date ((t (:foreground ,gruvbox-red))))
   `(magit-blame-hash ((t (:foreground ,gruvbox-teal))))
   `(magit-blame-heading ((t (:foreground ,gruvbox-orange :background ,gruvbox-base3 :extend t))))
   `(magit-branch-current ((t (:underline ,gruvbox-green :inherit magit-branch-local))))
   `(magit-branch-local ((t (:foreground ,gruvbox-teal))))
   `(magit-branch-remote ((t (:foreground ,gruvbox-green))))
   `(magit-cherry-equivalent ((t (:foreground ,gruvbox-violet))))
   `(magit-cherry-unmatched ((t (:foreground ,gruvbox-teal))))
   `(magit-diff-added ((t (:foreground ,gruvbox-yellow2 :background ,gruvbox-grey8 :extend t))))
   `(magit-diff-added-highlight ((t (:foreground ,gruvbox-vc-added :background ,gruvbox-grey14 :weight bold :extend t))))
   `(magit-diff-base ((t (:foreground ,gruvbox-orange6 :background ,gruvbox-grey10 :extend t))))
   `(magit-diff-base-highlight ((t (:foreground ,gruvbox-orange :background ,gruvbox-orange1 :weight bold :extend t))))
   `(magit-diff-context ((t (:foreground ,gruvbox-base3 :foreground ,gruvbox-base7))))
   `(magit-diff-context-highlight ((t (:foreground ,gruvbox-fg :background ,gruvbox-bg-alt :extend t))))
   `(magit-diff-file-heading ((t (:foreground ,gruvbox-fg :weight bold :extend t))))
   `(magit-diff-file-heading-selection ((t (:foreground ,gruvbox-dark-red :background ,gruvbox-dark-blue :weight bold :extend t))))
   `(magit-diff-hunk-heading ((t (:background ,gruvbox-base3 :foreground ,gruvbox-base7))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,gruvbox-bg-alt2 :foreground ,gruvbox-fg))))
   `(magit-diff-lines-heading ((t (:foreground ,gruvbox-yellow :background ,gruvbox-red :extend t :extend t))))
   `(magit-diff-removed ((t (:foreground ,gruvbox-red8 :background ,gruvbox-grey15 :extend t))))
   `(magit-diff-removed-highlight ((t (:foreground ,gruvbox-vc-deleted :background ,gruvbox-red4 :weight bold :extend t))))
   `(magit-diffstat-added ((t (:foreground ,gruvbox-vc-added))))
   `(magit-diffstat-removed ((t (:foreground ,gruvbox-vc-deleted))))
   `(magit-dimmed ((t (:foreground ,gruvbox-base7))))
   `(magit-filename ((t (:foreground ,gruvbox-violet))))
   `(magit-hash ((t (:foreground ,gruvbox-base6))))
   `(magit-header-line ((t (:background ,gruvbox-dark-blue :foreground ,gruvbox-base8 :weight bold :box (:line-width 3 :color ,gruvbox-dark-blue)))))
   `(magit-log-author ((t (:foreground ,gruvbox-orange))))
   `(magit-log-date ((t (:foreground ,gruvbox-blue))))
   `(magit-log-graph ((t (:foreground ,gruvbox-base6))))
   `(magit-process-ng ((t (:inherit error))))
   `(magit-process-ok ((t (:inherit success))))
   `(magit-reflog-amend ((t (:foreground ,gruvbox-dark-red))))
   `(magit-reflog-checkout ((t (:foreground ,gruvbox-blue))))
   `(magit-reflog-cherry-pick ((t (:foreground ,gruvbox-green))))
   `(magit-reflog-commit ((t (:foreground ,gruvbox-green))))
   `(magit-reflog-merge ((t (:foreground ,gruvbox-green))))
   `(magit-reflog-other ((t (:foreground ,gruvbox-teal))))
   `(magit-reflog-rebase ((t (:foreground ,gruvbox-dark-red))))
   `(magit-reflog-remote ((t (:foreground ,gruvbox-teal))))
   `(magit-reflog-reset ((t (:inherit error))))
   `(magit-refname ((t (:foreground ,gruvbox-base6))))
   `(magit-section-heading ((t (:foreground ,gruvbox-teal :weight bold))))
   `(magit-section-heading-selection ((t (:foreground ,gruvbox-orange :weight bold :extend t))))
   `(magit-section-highlight ((t (:inherit hl-line))))
   `(magit-section-secondary-heading ((t (:foreground ,gruvbox-violet :weight bold :extend t))))
   `(magit-sequence-drop ((t (:foreground ,gruvbox-red))))
   `(magit-sequence-head ((t (:foreground ,gruvbox-blue))))
   `(magit-sequence-part ((t (:foreground ,gruvbox-orange))))
   `(magit-sequence-stop ((t (:foreground ,gruvbox-green))))
   `(magit-signature-bad ((t (:inherit error))))
   `(magit-signature-error ((t (:inherit error))))
   `(magit-signature-expired ((t (:foreground ,gruvbox-orange))))
   `(magit-signature-good ((t (:inherit success))))
   `(magit-signature-revoked ((t (:foreground ,gruvbox-dark-red))))
   `(magit-signature-untrusted ((t (:foreground ,gruvbox-yellow))))
   `(magit-tag ((t (:foreground ,gruvbox-yellow))))
   `(marginalia-documentation ((t (:inherit font-lock-doc-face))))
   `(marginalia-file-priv-dir ((t (:foreground ,gruvbox-blue))))
   `(marginalia-file-priv-exec ((t (:foreground ,gruvbox-green))))
   `(marginalia-file-priv-link ((t (:foreground ,gruvbox-violet))))
   `(marginalia-file-priv-other ((t (:foreground ,gruvbox-dark-red))))
   `(marginalia-file-priv-rare ((t (:foreground ,gruvbox-fg))))
   `(marginalia-file-priv-read ((t (:foreground ,gruvbox-yellow))))
   `(marginalia-file-priv-write ((t (:foreground ,gruvbox-red))))
   `(marginalia-lighter ((t (:foreground ,gruvbox-violet))))
   `(marginalia-number ((t (:foreground ,gruvbox-violet))))
   `(marginalia-size ((t (:foreground ,gruvbox-violet))))
   `(markdown-blockquote-face ((t (:inherit italic :foreground ,gruvbox-base6))))
   `(markdown-bold-face ((t (:inherit bold :foreground ,gruvbox-orange))))
   `(markdown-code-face ((t (:background ,gruvbox-grey7 :extend t))))
   `(markdown-header-delimiter-face ((t (:foreground ,gruvbox-orange))))
   `(markdown-header-face ((t (:inherit bold :foreground ,gruvbox-green))))
   `(markdown-html-attr-name-face ((t (:inherit font-lock-variable-name-face))))
   `(markdown-html-attr-value-face ((t (:inherit font-lock-string-face))))
   `(markdown-html-entity-face ((t (:inherit font-lock-variable-name-face))))
   `(markdown-html-tag-delimiter-face ((t (:inherit markdown-markup-face))))
   `(markdown-html-tag-name-face ((t (:inherit font-lock-keyword-face))))
   `(markdown-inline-code-face ((t (:inherit (markdown-code-face markdown-pre-face) :extend nil))))
   `(markdown-italic-face ((t (:inherit italic :foreground ,gruvbox-violet))))
   `(markdown-link-face ((t (:inherit underline :foreground ,gruvbox-base6))))
   `(markdown-list-face ((t (:foreground ,gruvbox-base6))))
   `(markdown-markup-face ((t (:foreground ,gruvbox-fg))))
   `(markdown-metadata-key-face ((t (:foreground ,gruvbox-red))))
   `(markdown-pre-face ((t (:foreground ,gruvbox-teal))))
   `(markdown-reference-face ((t (:foreground ,gruvbox-doc-comments))))
   `(markdown-url-face ((t (:foreground ,gruvbox-violet))))
   `(match ((t (:foreground ,gruvbox-green :background ,gruvbox-base0 :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,gruvbox-teal))))
   `(mode-line ((t (:background ,gruvbox-modeline-bg :foreground ,gruvbox-doc-comments :box nil))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-buffer-id ((t (:weight bold))))
   `(mode-line-emphasis ((t (:foreground ,gruvbox-yellow :distant-foreground ,gruvbox-bg))))
   `(mode-line-highlight ((t (:inherit highlight :distant-foreground ,gruvbox-bg))))
   `(mode-line-inactive ((t (:background ,gruvbox-bg :foreground ,gruvbox-base4 :box nil))))
   `(nobreak-space ((t (:inherit escape-glyph :underline t))))
   `(orderless-match-face-0 ((t (:weight bold :foreground ,gruvbox-grey19 :background ,gruvbox-grey11))))
   `(orderless-match-face-1 ((t (:weight bold :foreground ,gruvbox-red18 :background ,gruvbox-grey6))))
   `(orderless-match-face-2 ((t (:weight bold :foreground ,gruvbox-yellow7 :background ,gruvbox-grey12))))
   `(orderless-match-face-3 ((t (:weight bold :foreground ,gruvbox-orange20 :background ,gruvbox-grey13))))
   `(org-agenda-clocking ((t (:background ,gruvbox-grey16))))
   `(org-agenda-date ((t (:foreground ,gruvbox-violet :weight ultra-bold))))
   `(org-agenda-date-today ((t (:foreground ,gruvbox-magenta5 :weight ultra-bold))))
   `(org-agenda-date-weekend ((t (:foreground ,gruvbox-magenta1 :weight ultra-bold))))
   `(org-agenda-dimmed-todo-face ((t (:foreground ,gruvbox-base6))))
   `(org-agenda-done ((t (:inherit org-done))))
   `(org-agenda-structure ((t (:foreground ,gruvbox-fg :weight ultra-bold))))
   `(org-archived ((t (:foreground ,gruvbox-doc-comments))))
   `(org-block ((t (:background ,gruvbox-base3 :extend t))))
   `(org-block-background ((t (:background ,gruvbox-base3 :extend t))))
   `(org-block-begin-line ((t (:inherit org-block :foreground ,gruvbox-base6))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-checkbox ((t (:inherit org-todo))))
   `(org-checkbox-statistics-done ((t (:inherit org-done))))
   `(org-checkbox-statistics-todo ((t (:inherit org-todo))))
   `(org-cite ((t (:foreground ,gruvbox-green3))))
   `(org-cite-key ((t (:foreground ,gruvbox-green5 :underline t))))
   `(org-code ((t (:inherit org-block :foreground ,gruvbox-orange))))
   `(org-date ((t (:foreground ,gruvbox-green))))
   `(org-default ((t (:inherit variable-pitch))))
   `(org-document-info ((t (:foreground ,gruvbox-red))))
   `(org-document-title ((t (:foreground ,gruvbox-red))))
   `(org-done ((t (:inherit org-headline-done :strike-through nil :weight bold))))
   `(org-drawer ((t (:foreground ,gruvbox-green8))))
   `(org-ellipsis ((t (:underline nil :foreground ,gruvbox-orange))))
   `(org-footnote ((t (:foreground ,gruvbox-orange))))
   `(org-formula ((t (:foreground ,gruvbox-green))))
   `(org-habit-alert-face ((t (:weight bold :background ,gruvbox-orange4))))
   `(org-habit-alert-future-face ((t (:weight bold :background ,gruvbox-orange2))))
   `(org-habit-clear-face ((t (:weight bold :background ,gruvbox-base4))))
   `(org-habit-clear-future-face ((t (:weight bold :background ,gruvbox-base3))))
   `(org-habit-overdue-face ((t (:weight bold :background ,gruvbox-red7))))
   `(org-habit-overdue-future-face ((t (:weight bold :background ,gruvbox-red2))))
   `(org-habit-ready-face ((t (:weight bold :background ,gruvbox-grey18))))
   `(org-habit-ready-future-face ((t (:weight bold :background ,gruvbox-grey17))))
   `(org-headline-done ((t (:foreground ,gruvbox-base5))))
   `(org-hide ((t (:foreground ,gruvbox-bg))))
   `(org-journal-calendar-entry-face ((t (:foreground ,gruvbox-dark-red :slant italic))))
   `(org-journal-calendar-scheduled-face ((t (:foreground ,gruvbox-red :slant italic))))
   `(org-journal-highlight ((t (:foreground ,gruvbox-yellow))))
   `(org-latex-and-related ((t (:foreground ,gruvbox-base8 :weight bold))))
   `(org-link ((t (:inherit link :foreground ,gruvbox-yellow))))
   `(org-list-dt ((t (:foreground ,gruvbox-teal))))
   `(org-meta-line ((t (:foreground ,gruvbox-base6))))
   `(org-pomodoro-mode-line ((t (:foreground ,gruvbox-red))))
   `(org-pomodoro-mode-line-overtime ((t (:foreground ,gruvbox-yellow :weight bold))))
   `(org-priority ((t (:foreground ,gruvbox-red))))
   `(org-property-value ((t (:foreground ,gruvbox-doc-comments))))
   `(org-quote ((t (:inherit italic :slant italic :foreground ,gruvbox-base7 :background ,gruvbox-grey9))))
   `(org-ref-acronym-face ((t (:foreground ,gruvbox-violet))))
   `(org-ref-cite-face ((t (:foreground ,gruvbox-yellow :weight light :underline t))))
   `(org-ref-glossary-face ((t (:foreground ,gruvbox-dark-red))))
   `(org-ref-label-face ((t (:foreground ,gruvbox-blue))))
   `(org-ref-ref-face ((t (:inherit link :foreground ,gruvbox-teal))))
   `(org-scheduled ((t (:foreground ,gruvbox-fg))))
   `(org-scheduled-previously ((t (:foreground ,gruvbox-base8))))
   `(org-scheduled-today ((t (:foreground ,gruvbox-base7))))
   `(org-sexp-date ((t (:foreground ,gruvbox-fg))))
   `(org-special-keyword ((t (:foreground ,gruvbox-doc-comments))))
   `(org-table ((t (:foreground ,gruvbox-teal))))
   `(org-tag ((t (:foreground ,gruvbox-orange5 :weight normal))))
   `(org-time-grid ((t (:foreground ,gruvbox-base6))))
   `(org-todo ((t (:foreground ,gruvbox-green :bold inherit))))
   `(org-upcoming-deadline ((t (:foreground ,gruvbox-orange16))))
   `(org-upcoming-distant-deadline ((t (:foreground ,gruvbox-orange7))))
   `(org-verbatim ((t (:foreground ,gruvbox-yellow))))
   `(org-warning ((t (:foreground ,gruvbox-yellow))))
   `(outline-1 ((t (:foreground ,gruvbox-violet :weight bold :extend t))))
   `(outline-2 ((t (:foreground ,gruvbox-teal :weight bold :extend t))))
   `(outline-3 ((t (:foreground ,gruvbox-green :weight bold :extend t))))
   `(outline-4 ((t (:foreground ,gruvbox-magenta3 :weight bold :extend t))))
   `(outline-5 ((t (:foreground ,gruvbox-green1 :weight bold :extend t))))
   `(outline-6 ((t (:foreground ,gruvbox-magenta5 :weight bold :extend t))))
   `(outline-7 ((t (:foreground ,gruvbox-green7 :weight bold :extend t))))
   `(outline-8 ((t (:foreground ,gruvbox-magenta6 :weight bold :extend t))))
   `(region ((t (:background ,gruvbox-bg-alt2 :distant-foreground ,gruvbox-orange14 :extend t))))
   `(secondary-selection ((t (:background ,gruvbox-base6 :extend t))))
   `(shadow ((t (:foreground ,gruvbox-base5))))
   `(show-paren-match ((t (:foreground unspecified :background ,gruvbox-base5 :bold t))))
   `(show-paren-mismatch ((t (:foreground unspecified :background "red"))))
   `(smerge-base ((t (:background ,gruvbox-grey16))))
   `(smerge-lower ((t (:background ,gruvbox-yellow1))))
   `(smerge-markers ((t (:background ,gruvbox-base6 :foreground ,gruvbox-bg :distant-foreground ,gruvbox-fg :weight bold))))
   `(smerge-mine ((t (:background ,gruvbox-red5))))
   `(smerge-other ((t (:background ,gruvbox-yellow1))))
   `(smerge-refined-added ((t (:inherit diff-added :inverse-video t))))
   `(smerge-refined-removed ((t (:inherit diff-removed :inverse-video t))))
   `(smerge-upper ((t (:background ,gruvbox-red5))))
   `(success ((t (:foreground ,gruvbox-green))))
   `(tab-bar ((t (:background ,gruvbox-bg-alt :foreground ,gruvbox-bg-alt :box nil))))
   `(tab-bar-tab ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg :box nil))))
   `(tab-bar-tab-inactive ((t (:inherit tab-line-tab :background ,gruvbox-bg-alt :foreground ,gruvbox-base7 :box nil))))
   `(tab-line ((t (:background ,gruvbox-bg-alt :foreground ,gruvbox-bg-alt :box nil))))
   `(tab-line-close-highlight ((t (:foreground ,gruvbox-yellow))))
   `(tab-line-highlight ((t (:inherit tab-line-tab))))
   `(tab-line-tab ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg :box nil))))
   `(tab-line-tab-current ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg))))
   `(tab-line-tab-inactive ((t (:inherit tab-line-tab :background ,gruvbox-bg-alt :foreground ,gruvbox-base7 :box nil))))
   `(tab-line-tab-inactive-alternate ((t (:inherit tab-line-tab-inactive))))
   `(tooltip ((t (:background ,gruvbox-bg-alt :foreground ,gruvbox-fg))))
   `(trailing-whitespace ((t (:background ,gruvbox-red))))
   `(vertical-border ((t (:background ,gruvbox-bg-alt2 :foreground ,gruvbox-bg-alt2))))
   `(vertico-current ((t (:background ,gruvbox-bg-alt2 :extend t))))
   `(vertico-posframe-border ((t (:background ,gruvbox-base6))))
   `(vertico-posframe-border-2 ((t (:background ,gruvbox-red))))
   `(vertico-posframe-border-3 ((t (:background ,gruvbox-green))))
   `(vertico-posframe-border-4 ((t (:background ,gruvbox-blue))))
   `(vertico-posframe-border-fallback ((t (:background ,gruvbox-yellow))))
   `(warning ((t (:foreground ,gruvbox-yellow))))
   `(which-key-command-description-face ((t (:foreground ,gruvbox-blue))))
   `(which-key-group-description-face ((t (:foreground ,gruvbox-red))))
   `(which-key-key-face ((t (:foreground ,gruvbox-green))))
   `(which-key-local-map-description-face ((t (:foreground ,gruvbox-orange))))
   `(widget-button-pressed ((t (:foreground ,gruvbox-red))))
   `(widget-documentation ((t (:foreground ,gruvbox-green))))
   `(widget-field ((t (:background ,gruvbox-base3 :distant-foreground ,gruvbox-bg :box (:line-width -1 :color ,gruvbox-base6) :extend t))))
   `(widget-single-line-field ((t (:background ,gruvbox-base3 :distant-foreground ,gruvbox-bg))))
   `(window-divider ((t (:inherit vertical-border))))
   `(window-divider-first-pixel ((t (:inherit window-divider))))
   `(window-divider-last-pixel ((t (:inherit window-divider))))
   `(window-tool-bar-button ((t (:background ,gruvbox-bg :foreground ,gruvbox-fg))))
   `(window-tool-bar-button-disabled ((t (:background ,gruvbox-bg-alt :foreground ,gruvbox-base7))))
   `(window-tool-bar-button-hover ((t (:inherit highlight :distant-foreground ,gruvbox-bg))))
   `(winum-face ((t (:inherit bold :foreground ,gruvbox-yellow))))
   `(xref-file-header ((t (:inherit success))))
   `(xref-line-number ((t (:foreground ,gruvbox-yellow))))
   `(xref-match ((t (:foreground ,gruvbox-green :background ,gruvbox-base0 :weight bold)))))

  (custom-theme-set-variables
   'gruvbox
   `(ansi-color-names-vector [,gruvbox-bg ,gruvbox-red ,gruvbox-green ,gruvbox-yellow ,gruvbox-blue ,gruvbox-dark-red ,gruvbox-teal ,gruvbox-fg])
   `(vc-annotate-color-map (list (cons 20 ,gruvbox-green) (cons 40 ,gruvbox-yellow4) (cons 60 ,gruvbox-yellow6) (cons 80 ,gruvbox-yellow) (cons 100 ,gruvbox-orange15) (cons 120 ,gruvbox-orange13) (cons 140 ,gruvbox-orange) (cons 160 ,gruvbox-orange8) (cons 180 ,gruvbox-red11) (cons 200 ,gruvbox-dark-red) (cons 220 ,gruvbox-red10) (cons 240 ,gruvbox-red13) (cons 260 ,gruvbox-red) (cons 280 ,gruvbox-red14) (cons 300 ,gruvbox-red15) (cons 320 ,gruvbox-red16) (cons 340 ,gruvbox-base5) (cons 360 ,gruvbox-base5)))
   `(vc-annotate-very-old-color nil)
   `(vc-annotate-background ,gruvbox-bg)))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'gruvbox)

;;; gruvbox-theme.el ends here
